### ISSUE TITLE
ads-lib 2.21.0 is incompatible with guava 19.0

### ISSUE THREAD

**Issue by markus-s24** [googleads/googleads-java-lib#101] opened 2016-10-28 14:43 UTC
As Guava 20 is not final yet, we have still Guava 19.0 hard-wired. With that, ads-lib (which depends on Guava 20.0-rc1) fails with:

java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;I)V
    at com.google.api.ads.adwords.lib.utils.ReportDownloadResponse.<init>(ReportDownloadResponse.java:47)

**Comment by jradcliff** [comment] 2016-10-28 15:47
Hi,

I just tried switching to Guava 19.0 in a local clone and I was able to **successfully** run the [DownloadCriteriaReport](https://github.com/googleads/googleads-java-lib/blob/master/examples/adwords_axis/src/main/java/adwords/axis/v201609/reporting/DownloadCriteriaReport.java) example via the following command:

```
mvn -X exec:java -Dexec.mainClass="adwords.axis.v201609.reporting.DownloadCriteriaReport"
```

Just to make sure I wasn't pulling in Guava 20.0 inadvertently, I checked via `mvn dependency:list` and I see the following in the output for Guava:

```
[INFO]    com.google.guava:guava:jar:19.0:compile
```

Could you double-check your dependencies and let me know which Java runtime you're using?

Thanks,
Josh, AdWords API Team

**Comment by markus-s24** [comment] 2016-10-29 09:25
Hi Josh,

I am not able to get the tests running on MacOS at all, so I cannot reproduce your test.
Anyway, did you compile against Guava 20.0-rc1 and run the test with Guava 19.0?

Markus

**Comment by markus-s24** [comment] 2016-10-29 09:54
Hi Josh,

this is not a compile time problem, but a runtime imcompatibility. 
Compiling against Guava 20 uses this method:
**public static void checkArgument(boolean, String, int)**
Compiling against Guava 19 use this compile time compatible version:
**public static void checkArgument(boolean, String, Object...)**
But this method is not runtime compatible with the signature of the Guava 20 method, resulting in the reported exception.

Markus

**Comment by jradcliff** [comment] 2016-11-01 18:52
Hi,

You're absolutely correct -- sorry about that. I thought I had configured both my compile time and runtime dependencies with 19.0, but clearly that wasn't the case. I just reproduced the error you described by using 19.0 at runtime.

I'll get this fixed in an upcoming release of the library. Thanks for pointing it out.

Cheers,
Josh, AdWords API Team

**Comment by jradcliff** [comment] 2016-11-09 22:03
Hi Markus,

It turns out your timing is impeccable! :)

While we were discussing this, [version 20.0 of Guava was released](https://mvnrepository.com/artifact/com.google.guava/guava/20.0) on Oct 28, 2016.

Given that `20` has graduated from release candidate, do you plan to move from `19` to `20`?

Thanks,
Josh, AdWords API Team

**Comment by markus-s24** [comment] 2016-11-11 08:51
Hi Josh,

we moved to Guava 20.0 and everything is fine.

Thanks,
Markus

**Closed** 2016-11-11 08:51 UTC
