### ISSUE TITLE
Trying to load ads.properties although it's not used

### ISSUE THREAD

**Issue by Olof-n** [googleads/googleads-java-lib#104] opened 2017-01-23 22:27 UTC
I'm having an issue that I've seen a few other persons having when googling for it. It seems to have been resolved but I can't really locate the solution to it.

My problem is that I'm trying to generate OfflineCredentials without passing the ads.properties by doing:

```
Credential oAuth2Credential = new OfflineCredentials.Builder()
                .forApi(OfflineCredentials.Api.ADWORDS)
                .withClientSecrets(clientId, clientSecret)
                .withRefreshToken(refreshToken)
                .build()
                .generateCredential();
```

But I get the error:

```
com.google.api.ads.common.lib.utils.logging.AdsServiceLoggers.ads_api_lib - Did not load optional configuration ads.properties:
com.google.api.ads.common.lib.conf.ConfigurationLoadException: Encountered a problem reading the provided configuration file "ads.properties"!
	at com.google.api.ads.common.lib.conf.ConfigurationHelper.fromFile(ConfigurationHelper.java:66)
	at com.google.api.ads.common.lib.conf.ConfigurationHelper.createCombinedConfiguration(ConfigurationHelper.java:151)
	at com.google.api.ads.common.lib.conf.ConfigurationProvider.get(ConfigurationProvider.java:67)
	at com.google.api.ads.common.lib.conf.ConfigurationProvider.get(ConfigurationProvider.java:31)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.google.api.ads.adwords.lib.utils.AdWordsInternals.<clinit>(AdWordsInternals.java:36)
	at com.google.api.ads.common.lib.auth.OfflineCredentials$Api.<clinit>(OfflineCredentials.java:66)
```

pom.xml is:

```       
 <dependency>
            <groupId>com.google.api-ads</groupId>
            <artifactId>ads-lib</artifactId>
            <version>2.22.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.api-ads</groupId>
            <artifactId>adwords-axis</artifactId>
            <version>2.22.0</version>
```

Help would be appreciated, or if you could point me to a solution to this

**Comment by jradcliff** [comment] 2017-01-23 22:33
Hi,

This looks like a duplicate of [issue 90](https://github.com/googleads/googleads-java-lib/issues/90). Could you review my comments there and reply to that issue if you have any further questions?

Thanks,
Josh, AdWords API Team

**Closed by jradcliff** 2017-01-23 22:33 UTC
