### ISSUE TITLE
 connection timed out: googleads.googleapis.com

### ISSUE THREAD

**Issue by levelmax** [googleads/googleads-java-lib#192] opened 2020-01-14 02:16 UTC
when i run ReachPlanServiceClient i got  information as follow.
it's looks like  `googleads.googleapis.com ` can't be connectioned
![image](https://user-images.githubusercontent.com/19588185/72307784-70a48780-36b6-11ea-9e99-5139b7ce09ef.png)

**Comment by nwbirnie** [comment] 2020-01-14 12:01
Looks like this is a dupe of the issue over [here](https://github.com/googleads/google-ads-java/issues/219). This is the issue tracker for the AdWords API SOAP library. Closing in favour of the Google Ads API client library bug.

**Closed by nwbirnie** 2020-01-14 12:01 UTC
