### ISSUE TITLE
Error while querying a table with V201802 

### ISSUE THREAD

**Issue by Sachpat** [googleads/googleads-java-lib#136] opened 2018-04-05 11:42 UTC
Hi I get the following exception while using the adwords v 201802 and the corresponding maven jars (3.13.0) : 
`Worker1_QueryProcessorQueue82) Error getting logged customer's data: java.lang.IllegalArgumentException
        at oracle.xml.jaxp.JXTransformer.setOutputProperty(JXTransformer.java:832) [xmlparserv2.jar:]
        at com.google.api.ads.common.lib.utils.logging.LoggingModule$TransformerSupplier.get(LoggingModule.java:126)
        at com.google.api.ads.common.lib.utils.logging.LoggingModule$TransformerSupplier.get(LoggingModule.java:111)
        at com.google.api.ads.common.lib.soap.RequestInfoXPathSet.parseMessage(RequestInfoXPathSet.java:80)
        at com.google.api.ads.common.lib.soap.axis.AxisHandler.invokeSoapCall(AxisHandler.java:245)
        at com.google.api.ads.common.lib.soap.SoapServiceClient.callSoapClient(SoapServiceClient.java:63)
        at com.google.api.ads.common.lib.soap.SoapServiceClient.invoke(SoapServiceClient.java:93)`

Can you tell me what might be wrong here?

**Comment by jradcliff** [comment] 2018-04-05 12:10
Hi,

That error is occurring at the following line of `LoggingModule`:

          transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "4");

Could you share some more information about your environment? For example, which JRE are you using, including the version?

Thanks,
Josh Radcliff, AdWords API Team

**Comment by Sachpat** [comment] 2018-04-05 12:47
Hi Josh, my JRE version is 1.7.0_79 basically java 7.

**Comment by jradcliff** [comment] 2018-04-05 12:54
Hi,

Thanks -- could you send over the output from `java -version` so I can see which particular Java7 JVM you're using?

Thanks,
Josh Radcliff, AdWords API Team

**Comment by Sachpat** [comment] 2018-04-05 13:03
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

- here you go.

**Comment by Sachpat** [comment] 2018-04-09 08:58
@jradcliff any updates on this? as the V201710's sunset point is not so far, wanted to get this version soon :)

**Comment by jradcliff** [comment] 2018-04-09 13:08
Hi,

Could you let me know the following?

1. Which version of the library you were using previously
1. Confirm that you do not see this error if you use that previous version in the same environment

I ask because the code that's leading to the error has been in place since 2016 and is not specific to v201802, so it's surprising that you'd get this error when upgrading to `3.13.0`.

Thanks,
Josh, AdWords API Team

**Comment by Sachpat** [comment] 2018-04-12 09:51
Hi @jradcliff , I was using v201710 that is 3.9.0 libraries before and I never saw this error before.

**Comment by Sachpat** [comment] 2018-04-12 12:46
Just FYI, it also gave the same error for 3.12.0 libraries.

**Comment by jradcliff** [comment] 2018-04-12 12:54
Thanks. Since you were using 3.9.0 previously, have you tried running the same request using 3.9.0 in the _same environment_ recently? I just want to rule out any environment changes that could have led to this error, so it would be good to know if 3.9.0 is still working for you.

Thanks,
Josh, AdWords API Team

**Comment by Sachpat** [comment] 2018-04-14 20:39
Hi, no it's the same environment . :) With the same Java version. Not sure why it fails with this version.

**Comment by Sachpat** [comment] 2018-04-16 13:08
@jradcliff can it be related to the oracle xml parser we use? I have been hearing about some issues with it in recently.

**Comment by jradcliff** [comment] 2018-04-16 13:18
That could definitely be the source of the problem. That error means that the XML toolkit doesn't recognize the `{http://xml.apache.org/xslt}indent-amount` property. Do you have the option of switching to a different parser to see if that resolves the issue?

Thanks,
Josh, AdWords API Team

**Comment by Sachpat** [comment] 2018-04-30 13:05
Hi @jradcliff , hmm I tried to look into the possibilities to switch to different parser, looks like it'S not that easy. Any other hints that would give me to tweak around?

**Comment by Sachpat** [comment] 2018-04-30 13:08
Basically to explain the scenarios better, there are few integration tests which also test the Adwords connection and all, they fail for only this version and not the previous ones. And, for a surprise once I successfully create a connection to adwords manually with some code or something. Everything starts to work fine that is the tests start passing.

**Comment by jradcliff** [comment] 2018-04-30 13:11
Hi,

I'm working on a change to the library so it will simply log those `IllegalArgumentExceptions` instead of throwing. I hope to have that ready for you soon.

In the meantime, you could:

1. Set the `javax.xml.transform.TransformerFactory` system property to your own implementation of [`TransformerFactory`](https://docs.oracle.com/javase/7/docs/api/javax/xml/transform/TransformerFactory.html)
2. Have your `TransformerFactory` return a `Transformer` that wraps the underlying `Transformer`, but ignores errors from `setOutputProperty` instead of throwing them.

Thanks,
Josh, AdWords API Team

**Comment by Sachpat** [comment] 2018-04-30 13:25
Thanks @jradcliff , I will wait for that. Yes in the meantime, I will try those workarounds too.

**Comment by Sachpat** [comment] 2018-05-09 15:47
@jradcliff , just to plan the update, can we expect this fix sometime soon? As the sunset point for v201710 is also coming near, wanted to get rid of this ASAP.

**Comment by marchelloUA** [comment] 2018-05-09 19:37
@jradcliff , any chance the sunset date for v201710 can be postponed till the problem is sorted out?

**Comment by jradcliff** [comment] 2018-05-10 15:38
Hi,

We plan to release a new version of the library with a fix for this issue next Tuesday (5/15) or Wednesday (5/16), so that should give sufficient time before the v201710 sunset.

In the meantime, have you tried the workarounds I mentioned earlier?

Thanks,
Josh, AdWords API Team

**Comment by Sachpat** [comment] 2018-05-16 12:40
Hi @jradcliff , thanks for the update yes this helped to solve the issue. This ticket can be closed now.

**Comment by jradcliff** [comment] 2018-05-16 12:56
Great - thanks for confirming!

**Closed by jradcliff** 2018-05-16 12:56 UTC
Labels: bug
